sources:
  - name: raw
    schema: raw
    tables:
      - name: matches
      - name: matchdays
      - name: standings
      - name: teams 
      - name: teamstats 
      - name: playerstats
      - name: lineups
      - name: lineup_events
      - name: feed_events
      - name: match_facts
      - name: match_officials
